name: Setup GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write
  
jobs:
  setup-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true
          token: ${{ github.token }}
      
      - name: Create empty artifact
        run: |
          mkdir -p ./dist
          echo "GitHub Pages Setup" > ./dist/index.html
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ github.token }} 